pub const AGENTS: [&'static str; 33] = [
    "Trigger",
    "Hugo",
    "Yanagi",
    "Lighter",
    "Caesar",
    "Soldier 11",
    "Nekomata",
    "Ben",
    "Anton",
    "Corin",
    "Billy",
    "Harumasa",
    "Miyabi",
    "Pulchra",
    "Piper",
    "Seth",
    "Lucy",
    "Soukaku",
    "Nicole",
    "Anby",
    "Soldier 0 - Anby",
    "Vivian",
    "Evelyn",
    "Astra Yao",
    "Jane",
    "Qingyi",
    "Zhu Yuan",
    "Rina",
    "Ellen",
    "Grace",
    "Burnice",
    "Lycaon",
    "Koleda",
];
